name: tst
description: "A new Flutter project."
publish_to: 'none' # Evita publicación accidental en pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4 # Asegúrate de que esta versión sea compatible con tu Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8 # Para iconos de estilo iOS
  fluttericon: ^2.0.0
  flutter_svg: ^2.0.14
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recomendado para buenas prácticas de código

flutter:
  uses-material-design: true
  # Especifica la carpeta de imágenes
  assets:
  - assets/myqr.png
  - assets/mitu.png
  - assets/profile.jpg
  - assets/icons/android.svg
  - assets/icons/kotlin.svg
  - assets/icons/react.svg
  - assets/icons/typescript.svg
  - assets/icons/linkedin.svg
  - assets/icons/firebase.svg
  - assets/icons/expo.svg
  


  # Para añadir fuentes personalizadas en el futuro:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
